services:
  backend:
    build:
      context: ./Backend/Nocodile/backend
      dockerfile: Dockerfile
    ports:
      - "${BACKEND_PORT:-8888}:8888"
    environment:
      - PYTHONUNBUFFERED=${PYTHONUNBUFFERED:-1}
      - PYTHONDONTWRITEBYTECODE=${PYTHONDONTWRITEBYTECODE:-1}
      - MYSQL_HOST=${MYSQL_HOST:-mysql}
      - MYSQL_USER=${MYSQL_USER:-root}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-object_detection}
      - MYSQL_PORT=${MYSQL_PORT:-3306}
      - QT_QPA_PLATFORM=offscreen
      - DISPLAY=:99
      - LIBGL_ALWAYS_SOFTWARE=1
    volumes:
      - ./Backend/Nocodile/backend:/app
      - backend-node-modules:/app/node_modules
      - ./Backend/Nocodile/backend/projects:/app/projects
      - ./Backend/Nocodile/backend/safe_projects:/app/safe_projects
    depends_on:
      - mysql
    networks:
      - nocodile-network
    restart: unless-stopped

  frontend:
    build:
      context: ./Frontend/Nocodile
      dockerfile: Dockerfile.frontend
    ports:
      - "${FRONTEND_PORT:-3001}:3000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL:-http://localhost:8888}
      - WATCHPACK_POLLING=true
    volumes:
      - ./Frontend/Nocodile/nocodile:/app
      - frontend-node-modules:/app/node_modules
      - frontend-next-cache:/app/.next
    networks:
      - nocodile-network
    depends_on:
      - backend
    restart: unless-stopped
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mysql:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD:-rootpassword}
      - MYSQL_DATABASE=${MYSQL_DATABASE:-nocodile_db}
      - MYSQL_USER=${MYSQL_USER:-nocodile}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD:-nocodilepassword}
    ports:
      - "3307:${MYSQL_PORT:-3306}"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./Backend/Nocodile/backend/database/scripts:/docker-entrypoint-initdb.d
    networks:
      - nocodile-network
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql-data:
    name: nocodile-mysql-data
  backend-node-modules:
    name: nocodile-backend-node-modules
  frontend-node-modules:
    name: nocodile-frontend-node-modules
  frontend-next-cache:
    name: nocodile-frontend-next-cache

networks:
  nocodile-network:
    driver: bridge
